"""Postgres-backed catalog repository.

Implements the bl.ports.LayersRepository protocol. The only module that
speaks SQL — everything above sees LayerMeta objects.

Connection URL and table name come from the runtime settings store on
every call, so UI settings changes apply without a restart. The table
identifier is validated + quoted by the store (never raw user input).
"""

from typing import List, Optional, Tuple

from psycopg.errors import UniqueViolation

from app.bl.ports.layer_meta import LayerMeta
from app.common.runtime_settings.runtime_settings_store import RuntimeSettingsStore
from app.dal.postgres import connect

_COLUMNS = "id, name, description, tags, provider, source_url"


class PostgresLayersRepository:
    def __init__(self, settings_store: RuntimeSettingsStore):
        self._store = settings_store

    def _select(self) -> str:
        return f"SELECT {_COLUMNS} FROM {self._store.get().quoted_layers_table()}"

    def list_layers(self) -> List[LayerMeta]:
        with connect(self._store) as conn:
            rows = conn.execute(self._select()).fetchall()
        return [self._to_meta(row) for row in rows]

    def get_layer(self, layer_id: str) -> Optional[LayerMeta]:
        with connect(self._store) as conn:
            row = conn.execute(
                self._select() + " WHERE id = %s", (layer_id,)
            ).fetchone()
        return self._to_meta(row) if row else None

    def add_layer(self, layer: LayerMeta) -> LayerMeta:
        settings = self._store.get()
        query = (
            f"INSERT INTO {settings.quoted_layers_table()} "
            "(name, description, tags, provider, source_url) "
            "VALUES (%s, %s, %s, %s, %s) RETURNING id"
        )
        try:
            with connect(self._store) as conn:
                row = conn.execute(
                    query,
                    (
                        layer.name,
                        layer.description,
                        layer.tags,
                        layer.provider,
                        layer.source_url,
                    ),
                ).fetchone()
        except UniqueViolation as exc:
            raise ValueError("A layer with this id already exists") from exc
        # Layer ids are strings at the BL boundary, while production catalogs
        # commonly use an integer/serial primary key generated by PostgreSQL.
        return layer.model_copy(update={"id": str(row["id"])})

    def upsert_layer(self, layer: LayerMeta) -> Tuple[LayerMeta, bool]:
        """Insert or update keyed on (provider, source_url) — the stable
        identity of an externally synced layer. Updates preserve tags
        (they may have been LLM-enriched after the original sync)."""
        table = self._store.get().quoted_layers_table()
        with connect(self._store) as conn:
            existing = conn.execute(
                f"SELECT id FROM {table} WHERE provider = %s AND source_url = %s",
                (layer.provider, layer.source_url),
            ).fetchone()
            if existing:
                conn.execute(
                    f"UPDATE {table} SET name = %s, description = %s WHERE id = %s",
                    (layer.name, layer.description, existing["id"]),
                )
                return layer.model_copy(update={"id": str(existing["id"])}), False
            row = conn.execute(
                f"INSERT INTO {table} "
                "(name, description, tags, provider, source_url) "
                "VALUES (%s, %s, %s, %s, %s) RETURNING id",
                (
                    layer.name,
                    layer.description,
                    layer.tags,
                    layer.provider,
                    layer.source_url,
                ),
            ).fetchone()
            return layer.model_copy(update={"id": str(row["id"])}), True

    @staticmethod
    def _to_meta(row: dict) -> LayerMeta:
        return LayerMeta(
            id=str(row["id"]),
            name=row["name"],
            description=row["description"] or "",
            tags=row["tags"] or [],
            provider=row["provider"],
            source_url=row["source_url"],
        )
