from typing import List, Optional, Protocol, Tuple

from app.bl.catalog.models.layer_meta import LayerMeta


class LayersRepository(Protocol):

    def list_layers(self) -> List[LayerMeta]: ...

    def get_layer(self, layer_id: str) -> Optional[LayerMeta]: ...

    def add_layer(self, layer: LayerMeta) -> LayerMeta: ...

    def update_layer_metadata(self, layer: LayerMeta) -> LayerMeta: ...

    def upsert_layer(self, layer: LayerMeta) -> Tuple[LayerMeta, bool]: ...     
